### ISSUE TITLE
Run a job at specific timestamp

### ISSUE THREAD

**Issue by alipiry** [davbeck/graphile-scheduler#4]
Hi @davbeck,
I have deleted_at column on `foo` table and I need to run a job at the mentioned deleted_at timestamp, how to do such thing with `graphile-scheduler`? is it even possible?

**Comment by davbeck** [comment]
There are 2 approaches you could take. First you could create a delayed job when `deleted_at` got set using Graphile Worker (no scheduler needed). You could do that either from the same process that sets `deleted_at` or in a hook. Or an approach that a lot of services take is to create a scheduled job that runs daily and cleans up items that were deleted that day.
