### ISSUE TITLE
only want to run task once, and then end

### ISSUE THREAD

**Issue by mingsterism** [davbeck/graphile-scheduler#7]
Hi, 
I want to run a task once, after X minutes, and then stop. 
Would graphile-scheduler be suitable for this. I noticed that it's aimed at running repeated times rather than just once. 

Thanks

**Comment by davbeck** [comment]
You don't need schedule for that. graphile-worker has that builtin. See the `runAt` option.

**Comment by mingsterism** [comment]
thanks very much  :)
Just what i needed
